#!/bin/bash
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/docmanager-extension/
echo '{"defaultViewers": {"markdown": "Markdown Preview"}}' > ~/.jupyter/lab/user-settings/@jupyterlab/docmanager-extension/plugin.jupyterlab-settings


